version: '3'
services:
  client-prod:
    build:
      context: ./client
      dockerfile: Dockerfile-production
    ports:
      - '80:80'
    depends_on:
      - server-prod
    volumes_from:
      - server-prod:ro

  server-prod:
    build:
      context: ./server
      dockerfile: Dockerfile-production
    environment:
      NODE_ENV: production
    ports:
      - '5000:5000'
    depends_on:
      - db-prod
    volumes:
      - /var/www/html/images:/var/www/html/images

  db-prod:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=squad-help-prod
    ports:
      - '5432:5432'

volumes:
  server-prod:
  nginx-server-prod:
